### ISSUE TITLE
Knot away logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#1]
https://drive.google.com/open?id=0BzVFl2mibGTnajZMMjdwaElkWVRyWkNZVk5MVFNfMkdKQW1B

Take this png and remove the silhouette of the girl so JUST THE TEXT remains, then upload it as a PNG to the same folder in drive. 

After that, put it in an oval shape and tweak it fit and balance well within that shape. Here's an example of the inspiration I'm talking about: 

![spa](https://cloud.githubusercontent.com/assets/539962/8753861/e0bc6fd0-2c73-11e5-8e52-de85867f8c12.jpg)

If you have to adjust the words, rearrange them, find the font she used to re-work the sizing as well without pixelation then do it. There are other versions of the Knot Away logo in the Google drive folder so feel free to crop and pull from those if need be. 

Upload 1 or 2 revisions to the Google drive.

Due date: 
7-19-15 12p

**Comment by AaronAguilar** [comment]
I've uploaded all images. One without the girl and just the text. Other two with two flower vectors.

https://drive.google.com/drive/u/0/folders/0BwBHyb7lC8cifjVXQTZoRGVoNTJrOFVHcDBkOVJIRnkxbHV0U1RjVWVoWHkxRklEV3FQZmc

there's a few different versions with different flower vector sizes.

**Comment by rodneystrong** [comment]
@AaronAguilar  Nice nice very nice! 

Which one of those do you hope the client likes?

**Comment by AaronAguilar** [comment]
The first one with the lotus flower in it. If I remember correctly, she had a lotus flower background pattern on her website.

**Comment by rodneystrong** [comment]
@AaronAguilar *nods  

Could you please create a 'logo sheet' for these and upload them to the drive? 

Thanks!

**Comment by AaronAguilar** [comment]
@rodneystrong Done. https://drive.google.com/drive/u/0/folders/0BwBHyb7lC8cifjVXQTZoRGVoNTJrOFVHcDBkOVJIRnkxbHV0U1RjVWVoWHkxRklEV3FQZmc

**Comment by rodneystrong** [comment]
: (  You forgot to include the version that is just the text alone. Please recreate and upload another logo sheet with the text-only version included.

Also, I'd like to discuss adjustments to the other ones.

**Comment by AaronAguilar** [comment]
I uploaded two new versions. One that has the lady again but the color fits more with the font and another with the lotus on top of everything. 

It can be found: https://drive.google.com/drive/u/0/folders/0BwBHyb7lC8cifjVXQTZoRGVoNTJrOFVHcDBkOVJIRnkxbHV0U1RjVWVoWHkxRklEV3FQZmc

**Comment by rodneystrong** [comment]
@AaronAguilar Wow, excellent work!! Much better choice on the gradient. Not too in your face but still noticeable to the discerning eye. Props.

Now please create the 'logo sheet' and replace the old one in the drive.

**Comment by AaronAguilar** [comment]
Logo sheet uploaded: https://drive.google.com/drive/u/0/folders/0BwBHyb7lC8cifjVXQTZoRGVoNTJrOFVHcDBkOVJIRnkxbHV0U1RjVWVoWHkxRklEV3FQZmc

As for the just text -- do you mean this one? 

https://drive.google.com/drive/u/0/folders/0BwBHyb7lC8cifjVXQTZoRGVoNTJrOFVHcDBkOVJIRnkxbHV0U1RjVWVoWHkxRklEV3FQZmc

**Comment by rodneystrong** [comment]
Good work sir. 

And yes, I did.
