### ISSUE TITLE
Center the slide text as it resizes down to phone size

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#10]
Make sure the text on each slide is centered as the browser width is resized down.

If the bg oval has to get cut off, then make sure it's evenly cut off on both the left and right sides. 

due date:
7-31-15   11p

**Comment by AaronAguilar** [comment]
Done. It's also a bit more to the top as well. 
http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
Perfect, love it. Thank you!
