### ISSUE TITLE
Add reCapcha code

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#12]
Step 1: client-side integration

Paste this snippet before the closing </head> tag on your HTML template:
````
<script src='https://www.google.com/recaptcha/api.js'></script>
````
Paste this snippet at the end of the ````<form>```` where you want the reCAPTCHA widget to appear:

````
<div class="g-recaptcha" data-sitekey="6Lf_wAoTAAAAACFkcMt6nUiUnwqdPBhzWQm8fkZX"></div>
````

due:

8-3-15   10p

**Comment by AaronAguilar** [comment]
Done. a40f193130c9074485a8782b104dba9a6f4dc829

**Comment by rodneystrong** [comment]
thank you thank you
