### ISSUE TITLE
spacing issues

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#14]
some sections have too much spacing in-between. screenshots below; but these aren't the only spacing issues. please go through the site and check for these similar spacing issues and correct them. they are not consistent, so please make the spacing consistent. 

![space](https://cloud.githubusercontent.com/assets/539962/9071660/597cb84a-3aab-11e5-93eb-0886fa9731d5.jpg)
![spac](https://cloud.githubusercontent.com/assets/539962/9071661/59832f4a-3aab-11e5-85de-dea0f5ad1909.jpg)

due:
8-4-15   8p

**Comment by AaronAguilar** [comment]
Done. 619aa0b2a5f45b21e3f05b86d7f33944464cd0ea

But you could check out the live version at http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
excellent work dude. 

i like how you changed the position of the anchor div to make it so when a user clicks a link in the top nav, the logo doesn't cover up the title of that section when it goes to it.
