### ISSUE TITLE
update pricing

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#16]
linda sent updated pricing for her services. 

please update according to the image below:

![kat_services_back_edited-2](https://cloud.githubusercontent.com/assets/539962/9153902/e96d3ce4-3e2b-11e5-9a03-a232fd5ce36a.jpg)

due:

8-11-15     12p

**Comment by AaronAguilar** [comment]
It's done: http://editllc.github.io/client-knot-away/

I took of the min-massage prices she had in the first section as they didn't match the updated prices. However, I do have a question. Is she okay with all other prices? Stress Smasher also doesn't have a price on it.

**Comment by rodneystrong** [comment]
I just confirmed with her that she's going to remove "stress smasher". So, please remove it ;D

**Comment by AaronAguilar** [comment]
Updated!
