### ISSUE TITLE
Find 2 more images

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#17]
Linda wants 2 more images for the top slider:

Hot stones 

sugar foot scrub

If you can find free options please do. 

Upload them to the google drive and crop them into the slider as well please.  
Post the link where you got each image from here as well please.

due:
8-26-15  10p

**Comment by AaronAguilar** [comment]
Two images - one of a stone massage and one of a foot massage, I couldn't find any sugar foot scrub, but I'm sure it gets the idea across.
Google link - https://drive.google.com/file/d/0BwNEeMVrMpDLYmRSOFhHVDAxa00/view?usp=sharing
https://drive.google.com/file/d/0BwNEeMVrMpDLTWxvd2dSaExSTFU/view?usp=sharing

Live update: 
http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
Good finds! 

Also, could you please post the link where you got each image from as well? 

Thanks

**Comment by AaronAguilar** [comment]
Food -  https://pixabay.com/en/foot-massage-foot-reflexology-740206/

Stone - https://pixabay.com/en/massage-relaxation-massage-389727/

**Comment by rodneystrong** [comment]
"food" ?? you think of feet as food? bro you trippin.

**Comment by AaronAguilar** [comment]
I'm hungry :(

**Comment by rodneystrong** [comment]
You stay away from my feet then...

**Comment by rodneystrong** [comment]
thank you again for this
