### ISSUE TITLE
Spelling error on slide

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#19]
Please fix this spelling error:
![screenshot_2015-09-13-17-01-07](https://cloud.githubusercontent.com/assets/539962/9839872/50216be8-5a3a-11e5-8ec8-02cd5e32f049.png)

And push it to live (FTP)

due:
9-13-15  11p

**Comment by AaronAguilar** [comment]
Sorry, I didn't get the email on my phone for some reason, however, it's updated and live.

**Comment by rodneystrong** [comment]
no worries, thanks for fixing this!
