### ISSUE TITLE
screenshot entire site + download site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#2]
take screenshots of all the pages on the current client's live site (use a screen capture software that captures the FULL LENGTH of the page; dont waste time screenshotting a section at a time and then combining them in photoshop)

download their entire site as well ( @AaronAguilar can show you how to do this )

upload everything to the appropriate folder in google drive

due date:
7-22-15  11a

**Comment by purplyrocky** [comment]
done
https://drive.google.com/open?id=0B_lfcedxYUvffjljejMwdHZIUnRsQWUzZzhlVVBuVjZBUWs2T3VLZkE5ZkF6cHFjeHVqMkU
