### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jarantfos** [EditLLC/client-knot-away#24]
should be "just massages for you" not "just messages for you"

due:
12-30-15  4p

**Comment by rodneystrong** [comment]
NICE!!  good catch there jared. Thanks for creating this issue for yourself too. I'll attach a due date for this.

due:
12-30-15  4p

**Comment by jarantfos** [comment]
Just fixed it on master and gh-pages, I'll FTP it in a few hours when I'm back

**Comment by jarantfos** [comment]
Fixed, ftp'd, etc
