### ISSUE TITLE
Let's try a version of the header with the logo in the middle 

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#3]
Comment out the header code and create a new version with the logo in the middle and "home" + "services" on the left and "about" + "contact" on the right (yes, leave out the "blog"). 

Don't forget to also test for responsiveness. When the window resizes down, you can revert to the old  behavior of the menu turning into the pancake symbol on the right and the logo moving to the left.

due date: 
7-28-15  5p

**Comment by AaronAguilar** [comment]
Centered the logo. Here's what it looks like so far. http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
It's not centered bro. Please keep trying to center it.

**Comment by AaronAguilar** [comment]
Updated: http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
Good job!! But there's a problem when resizing.. 

At 1011px width the logo seems to clone itself and the nav items get pushed into the picture. This happens until 1090px width. 

Please fix this by tonight 11p.

**Comment by AaronAguilar** [comment]
Update. I made the thing hide before it hits the other resolution. http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
Good job sir. Thanks for fixing all the resizing issues!!
