### ISSUE TITLE
Can't change/add labels

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#4]
I can't change or add any labels in any of the client-* repos we have. 

Could you please make it so I can?  

Thanks!

**Comment by irms** [comment]
@rodneystrong made you an owner of the Github organization. You should have rights to everything now.

**Comment by rodneystrong** [comment]
![un](https://cloud.githubusercontent.com/assets/539962/8940829/d276c51e-3520-11e5-97a4-3e40a9e0cac9.jpg)

**Comment by rodneystrong** [comment]
Thank you ma'am
