### ISSUE TITLE
Images used for Knot Away

### ISSUE THREAD

**Issue by AaronAguilar** [EditLLC/client-knot-away#5]
Woman getting a massage --
https://pixabay.com/en/wellness-massage-relax-relaxing-285587/

Second woman getting a massage -- 
https://pixabay.com/en/physiotherapy-massage-back-567021/

Rock massage -- 
https://pixabay.com/en/massage-relaxation-massage-389719/

Flower & Towel --
https://pixabay.com/en/wellness-massage-relax-relaxing-589770/

**Comment by rodneystrong** [comment]
Excellent @AaronAguilar , thank you sir!
