### ISSUE TITLE
Add Yelp review widget

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#6]
Similar to how we implemented the Yelp review widget on the lavogue site, do the same for this site. 

Find a good spot to put it and then comment here when it's uploaded to gh-pages.

due date:
7-29-15   11a

**Comment by AaronAguilar** [comment]
Added the Yelp widget. http://editllc.github.io/client-knot-away/

**Comment by rodneystrong** [comment]
Good stuff Aaron! Nice work.
