### ISSUE TITLE
"What Others Have To Say" text is not centered

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#7]
Please center it. 

Look at the other sections on the site and see how the title text is centered, then replicate that for this section with the Yelp widget in it. 

![center](https://cloud.githubusercontent.com/assets/539962/8948820/524e009c-3560-11e5-9f7f-a1f1b28f1210.jpg)

Remember, "attention to detail" Aaron. Please notice these minor issues and resolve them as you're working on the site.

due date: 
7-29-15    3p

**Comment by AaronAguilar** [comment]
Fixed, it's now the same as every section header.

**Comment by rodneystrong** [comment]
excellent work as always sir!
