### ISSUE TITLE
slider image repeats on larger resolutions

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#8]
![off](https://cloud.githubusercontent.com/assets/539962/8948870/ef37e792-3560-11e5-86f7-b610e64a194d.jpg)

The slideshow image repeats when the resolution is really wide. Please make it so the image does not repeat. 

due date:
7-29-15     3p

**Comment by AaronAguilar** [comment]
fixed. Images don't repeat, no matter the resolution.

**Comment by rodneystrong** [comment]
Goooood work sir. I like how you used background-size: cover. 

Can you tell me the difference between background-size: cover and background-size: contain ?
