### ISSUE TITLE
Try a version with logo sticking out the bottom

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-knot-away#9]
I mentioned this to you earlier and you claimed this was an idea you had but didn't do it because you thought I wouldn't like it. 

Well do it and show me. Make the logo larger and have some of the bottom portion of it extend beyond the bottom of the background-color.

![down](https://cloud.githubusercontent.com/assets/539962/8950041/d75341d4-3570-11e5-8670-6acca099d545.jpg)

due date:
7-29-15     5p

**Comment by AaronAguilar** [comment]
Done! http://editllc.github.io/client-knot-away/
I have it to where it disappears when small and then another one takes it's place on top of the navigation (so it doesn't show when toggle'd).

**Comment by rodneystrong** [comment]
Again, good work sir. Great job on the box-shadow effect; subtle yet still noticeable and effective. Great job on lining it for being perfectly centered.
